version: '2'
services:
  #kafka related
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - argedor
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    networks:
      - argedor
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10

  producer:
    image: producer:latest
    build: ./producer
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - argedor
    environment:
      KAFKA_BROKER: kafka:9092
      TOPIC: deneme

  consumer:
    image: consumer:latest
    build: ./consumer
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - argedor
    environment:
      KAFKA_BROKER: kafka:9092
      TOPIC: deneme
      THREAD_COUNT: 5

networks:
  argedor: